---
- name: Ensure sample directory exists
  win_file:
    path: C:\Users\{{ username }}\Downloads\sample
    state: directory

- name: Copy website files
  win_copy:
    src: ../website
    dest: C:\Users\{{ username }}\Downloads\sample
