---
- name: Run HTTP Server if not running already
  win_shell: |
    if (-not (Get-Process -Name "python" -ErrorAction SilentlyContinue)) {
      Start-Process "python" "-m http.server -b 192.168.1.8 8080" -WindowStyle Hidden
    }
  args:
    chdir: C:\Users\{{ username }}\Downloads\sample\website
  changed_when: false
